
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 31 17:57:11 BST 2013
//----------------------------------------------------

package frontend.parser;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int INTEGER_LITERAL = 6;
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int MINUS = 3;
  public static final int DIVIDE = 4;
  public static final int TIMES = 5;
  public static final int EOF = 0;
}

