
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 21 18:42:08 BST 2013
//----------------------------------------------------

package frontend.parser;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int DIVIDE = 5;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int EQ = 2;
  public static final int error = 1;
  public static final int IDENTIFIER = 8;
  public static final int TIMES = 6;
  public static final int INTEGER_LITERAL = 7;
}

